package com.codi.laolaiqiao.domain;

public class Constant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant.id
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant.category
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant.const_key
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    private String constKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant.const_value
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    private String constValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant.remark
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant.extra_column
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    private String extraColumn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant.id
     *
     * @return the value of constant.id
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant.id
     *
     * @param id the value for constant.id
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant.category
     *
     * @return the value of constant.category
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant.category
     *
     * @param category the value for constant.category
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant.const_key
     *
     * @return the value of constant.const_key
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public String getConstKey() {
        return constKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant.const_key
     *
     * @param constKey the value for constant.const_key
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public void setConstKey(String constKey) {
        this.constKey = constKey == null ? null : constKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant.const_value
     *
     * @return the value of constant.const_value
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public String getConstValue() {
        return constValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant.const_value
     *
     * @param constValue the value for constant.const_value
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public void setConstValue(String constValue) {
        this.constValue = constValue == null ? null : constValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant.remark
     *
     * @return the value of constant.remark
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant.remark
     *
     * @param remark the value for constant.remark
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant.extra_column
     *
     * @return the value of constant.extra_column
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public String getExtraColumn() {
        return extraColumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant.extra_column
     *
     * @param extraColumn the value for constant.extra_column
     *
     * @mbggenerated Mon Dec 26 14:28:14 CST 2016
     */
    public void setExtraColumn(String extraColumn) {
        this.extraColumn = extraColumn == null ? null : extraColumn.trim();
    }
}