package com.codi.laolaiqiao.domain;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_mobile
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String userMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_card
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String userCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_email
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_password
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_state
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_date
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_updated_date
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private Date lastUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_updated_user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String lastUpdatedUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.is_valid
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private Boolean isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.external_client_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String externalClientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_from
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String userFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sex
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.reference
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.region
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.region_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.street
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.street_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String streetCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.community
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.hobby
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private String hobby;
    
    private String imageUrl;
    
    
    private String openId;
    
    
    public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_mobile
     *
     * @return the value of user.user_mobile
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_mobile
     *
     * @param userMobile the value for user.user_mobile
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_card
     *
     * @return the value of user.user_card
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getUserCard() {
        return userCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_card
     *
     * @param userCard the value for user.user_card
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setUserCard(String userCard) {
        this.userCard = userCard == null ? null : userCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_password
     *
     * @return the value of user.login_password
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_password
     *
     * @param loginPassword the value for user.login_password
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_state
     *
     * @return the value of user.user_state
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_state
     *
     * @param userState the value for user.user_state
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_date
     *
     * @return the value of user.create_date
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_date
     *
     * @param createDate the value for user.create_date
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_user_id
     *
     * @return the value of user.create_user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_user_id
     *
     * @param createUserId the value for user.create_user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_updated_date
     *
     * @return the value of user.last_updated_date
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_updated_date
     *
     * @param lastUpdatedDate the value for user.last_updated_date
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_updated_user_id
     *
     * @return the value of user.last_updated_user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getLastUpdatedUserId() {
        return lastUpdatedUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_updated_user_id
     *
     * @param lastUpdatedUserId the value for user.last_updated_user_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setLastUpdatedUserId(String lastUpdatedUserId) {
        this.lastUpdatedUserId = lastUpdatedUserId == null ? null : lastUpdatedUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.is_valid
     *
     * @return the value of user.is_valid
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public Boolean getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.is_valid
     *
     * @param isValid the value for user.is_valid
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setIsValid(Boolean isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.external_client_id
     *
     * @return the value of user.external_client_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getExternalClientId() {
        return externalClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.external_client_id
     *
     * @param externalClientId the value for user.external_client_id
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setExternalClientId(String externalClientId) {
        this.externalClientId = externalClientId == null ? null : externalClientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_from
     *
     * @return the value of user.user_from
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getUserFrom() {
        return userFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_from
     *
     * @param userFrom the value for user.user_from
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setUserFrom(String userFrom) {
        this.userFrom = userFrom == null ? null : userFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sex
     *
     * @return the value of user.sex
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sex
     *
     * @param sex the value for user.sex
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.reference
     *
     * @return the value of user.reference
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.reference
     *
     * @param reference the value for user.reference
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province_code
     *
     * @return the value of user.province_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province_code
     *
     * @param provinceCode the value for user.province_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city_code
     *
     * @return the value of user.city_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city_code
     *
     * @param cityCode the value for user.city_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.region
     *
     * @return the value of user.region
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.region
     *
     * @param region the value for user.region
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.region_code
     *
     * @return the value of user.region_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.region_code
     *
     * @param regionCode the value for user.region_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode == null ? null : regionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.street
     *
     * @return the value of user.street
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.street
     *
     * @param street the value for user.street
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.street_code
     *
     * @return the value of user.street_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getStreetCode() {
        return streetCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.street_code
     *
     * @param streetCode the value for user.street_code
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setStreetCode(String streetCode) {
        this.streetCode = streetCode == null ? null : streetCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.community
     *
     * @return the value of user.community
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.community
     *
     * @param community the value for user.community
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.hobby
     *
     * @return the value of user.hobby
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.hobby
     *
     * @param hobby the value for user.hobby
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}