package com.codi.laolaiqiao.domain;

import java.util.Date;

public class WechatNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_news.id
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_news.news_title
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_news.news_description
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    private String newsDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_news.news_picUrl
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    private String newsPicurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_news.news_url
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    private String newsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_news.remark
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    private String remark;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_updated_date
     *
     * @mbggenerated Thu Dec 22 21:39:03 CST 2016
     */
    private Date lastUpdatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_news.id
     *
     * @return the value of wechat_news.id
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_news.id
     *
     * @param id the value for wechat_news.id
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_news.news_title
     *
     * @return the value of wechat_news.news_title
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_news.news_title
     *
     * @param newsTitle the value for wechat_news.news_title
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_news.news_description
     *
     * @return the value of wechat_news.news_description
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public String getNewsDescription() {
        return newsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_news.news_description
     *
     * @param newsDescription the value for wechat_news.news_description
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public void setNewsDescription(String newsDescription) {
        this.newsDescription = newsDescription == null ? null : newsDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_news.news_picUrl
     *
     * @return the value of wechat_news.news_picUrl
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public String getNewsPicurl() {
        return newsPicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_news.news_picUrl
     *
     * @param newsPicurl the value for wechat_news.news_picUrl
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public void setNewsPicurl(String newsPicurl) {
        this.newsPicurl = newsPicurl == null ? null : newsPicurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_news.news_url
     *
     * @return the value of wechat_news.news_url
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public String getNewsUrl() {
        return newsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_news.news_url
     *
     * @param newsUrl the value for wechat_news.news_url
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public void setNewsUrl(String newsUrl) {
        this.newsUrl = newsUrl == null ? null : newsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_news.remark
     *
     * @return the value of wechat_news.remark
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_news.remark
     *
     * @param remark the value for wechat_news.remark
     *
     * @mbggenerated Thu Dec 29 16:09:55 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }
    
}